---
- name: Ensure SNMP is installed
  tags:
    - setup_snmp
  apt:
    name: snmpd
    state: present

- name: Ensure SNMP is enabled
  tags:
    - setup_snmp
  service:
    name: snmpd
    enabled: yes

- name: Backup existing snmpd.conf
  tags:
    - setup_snmp
  copy:
    src: /etc/snmp/snmpd.conf
    dest: /etc/snmp/snmpd.conf.bak
    remote_src: yes
    backup: yes

- name: Configure snmpd.conf for read-write access
  tags:
    - setup_snmp
  copy:
    dest: /etc/snmp/snmpd.conf
    content: |
      sysLocation    LX
      sysContact     lxuser <lxuser@lx.local>
      sysServices    72
      master  agentx
      agentaddress  udp:161,udp6:[::1]:161
      view   systemonly  included   .1.3.6.1.2.1.1
      view   systemonly  included   .1.3.6.1.2.1.25.1
      rocommunity  public default -V systemonly
      rocommunity6 public default -V systemonly
      rwcommunity private 
      rocommunity public 127.0.0.1
      view all included .1 80
      access notConfigGroup "" any noauth exact all none none
      rouser authPrivUser authpriv -V systemonly
      includeDir /etc/snmp/snmpd.conf.d

- name: Restart SNMP daemon to apply changes
  tags:
    - setup_snmp
  service:
    name: snmpd
    state: restarted
